test: change code 88

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -17,31 +17,33 @@ jobs:
       VERCEL_SCOPE: 1212evgen
 
     steps:
-    - name: 'Checkout'
-      uses: actions/checkout@v4
+      - name: 'Checkout'
+        uses: actions/checkout@v4
+        with:
+          persist-credentials: false
 
-    - name: 'Setup Node.js v20'
-      uses: actions/setup-node@v4
-      with:
-        node-version: 20
+      - name: 'Setup Node.js v20'
+        uses: actions/setup-node@v4
+        with:
+          node-version: 20
 
-    - name: 'Install dependencies'
-      run: npm install --global vercel@33 semantic-release@22 @semantic-release/git@10 @semantic-release/changelog@6
+      - name: 'Install dependencies'
+        run: npm install --global vercel@33 semantic-release@22 @semantic-release/git@10 @semantic-release/changelog@6 @semantic-release/exec@6
 
-    - name: 'Pull Vercel project settings'
-      run: vercel pull --environment=production --yes --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ env.VERCEL_SCOPE }}
+      - name: 'Pull Vercel project settings'
+        run: vercel pull --environment=production --yes --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ env.VERCEL_SCOPE }}
 
-    - name: 'Build project artifacts'
-      run: |
-        vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ env.VERCEL_SCOPE }}
-        (cd .vercel/output && zip ../../build.zip . -r)
+      - name: 'Build project artifacts'
+        run: |
+          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ env.VERCEL_SCOPE }}
+          (cd .vercel/output && zip ../../build.zip . -r)
 
-    - name: 'Generate `semantic-release` config'
-      run: |
-        cat <<EOF | tee .releaserc
+      - name: 'Generate `semantic-release` config'
+        run: |
+          cat <<EOF | tee .releaserc
           {
             "branches": [
-              "+([0-9])?(.{+([0-9]),x}).x",
+              "+([0-9]).+([0-9]).+([0-9])",
               "main"
             ],
             "plugins": [
@@ -54,12 +56,27 @@ jobs:
                 "assets": [
                   { "path": "build.zip", "label": "Build (zip)" }
                 ]
+              }],
+              ["@semantic-release/exec", {
+                "successCmd": "echo \${ nextRelease.version } > version.txt"
               }]
             ]
           }
-        EOF
+          EOF
 
-    - name: 'Release'
-      run: npx semantic-release --debug
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: 'Release'
+        run: npx semantic-release --debug
+        env:
+          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
+          GIT_AUTHOR_NAME: "12evgen-bot"
+          GIT_AUTHOR_EMAIL: "12evgen@mail.ru"
+          GIT_COMMITTER_NAME: "12evgen-bot"
+          GIT_COMMITTER_EMAIL: "12evgen@mail.ru"
+
+      - name: 'Validate release'
+        shell: bash
+        run: >
+          if [[ ! -f version.txt ]]; then
+            echo "version.txt was not created, release aborted" 1>&2;
+            exit 1;
+          fi
